# Generated by Django 2.2.6 on 2020-07-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('News_type', models.CharField(max_length=150)),
                ('P_type', models.CharField(max_length=50)),
                ('p_desc', models.CharField(max_length=750)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=150)),
                ('p_price', models.IntegerField(max_length=50)),
                ('P_type', models.CharField(max_length=50)),
                ('p_category', models.CharField(max_length=50)),
                ('p_subcategory', models.CharField(max_length=50)),
                ('p_quantity', models.IntegerField(max_length=50)),
                ('p_desc', models.CharField(max_length=750)),
                ('p_warranty', models.CharField(max_length=150)),
                ('publish_date', models.DateField()),
                ('p_img', models.ImageField(default='product_img/noProductImage.jpg', upload_to='product_img/')),
            ],
        ),
    ]
