# Generated by Django 2.2.6 on 2020-07-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200724_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrailer_Detail',
            fields=[
                ('retrailer_id', models.AutoField(primary_key=True, serialize=False)),
                ('retrailer_name', models.CharField(max_length=150)),
                ('retrailer_phone', models.CharField(max_length=20)),
                ('retrailer_address', models.CharField(max_length=150)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='p_desc',
            new_name='News_desc',
        ),
        migrations.RemoveField(
            model_name='news',
            name='P_type',
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='p_img',
            field=models.ImageField(default='product_img/noProductImage.png', upload_to='product_img/'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='p_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='p_subcategory',
            field=models.CharField(default='No Subcategory', max_length=50),
        ),
    ]
