# Generated by Django 2.2.6 on 2020-09-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200730_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='p_company',
            field=models.CharField(default='havells', max_length=200),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='p_quantity',
            field=models.IntegerField(),
        ),
    ]
